[theme]
primaryColor = "#4f46e5"
backgroundColor = "#f8fafc"
secondaryBackgroundColor = "#ffffff"
textColor = "#1f2937"
font = "Inter"

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false 
